Models/Crew/CrewViewModel.cs
using Microsoft.Extensions.Localization;

namespace sailwithdivine.com.Models.Crew
{
    public class CrewViewModel
    {
        public string Title { get; set; }
    }
}

Models/Home/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime;
using System.Threading.Tasks;

namespace sailwithdivine.com.Models.Home
{
    public class HomeViewModel
    {
        public string IconShipText { get; set; }
        public string IconInstagramText { get; set; }
        public string IconCrewText { get; set; }
        public string IconContactUsText { get; set; }
        public string PositionText { get; set; }
        public string PositionButtonText { get; set; }
        public string CountdownTitle { get; set; }
        public string CountdownDays { get; set; }
    }
}

Controllers/BoatController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using sailwithdivine.com.Models.Boat;
using System.Linq;

namespace sailwithdivine.com.Controllers
{
    public class BoatController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IStringLocalizer<Resource> _localizer;

        public BoatController(IWebHostEnvironment webHostEnvironment, IStringLocalizer<Resource> localizer)
        {
            _webHostEnvironment = webHostEnvironment;
            _localizer = localizer;
        }
        public IActionResult Index()
        {
            var model = new BoatViewModel
            {
                ImageUrls = _webHostEnvironment.WebRootFileProvider.GetDirectoryContents("Content/Boat/Interior/")
                .Select(x => $"../Content/Boat/Interior/{x.Name}").ToList(),
                Title = _localizer["Boat.Title"],
                Subtitle = _localizer["Boat.Subtitle"],
                InteriorTitle = _localizer["Boat.Interior.Title"],
                InteriorText = _localizer["Boat.Interior.Text"],
                LayoutTitle = _localizer["Boat.Layout.Title"],
                LayoutText = _localizer["Boat.Layout.Text"],
                EquipmentTitle = _localizer["Boat.Equipment.Title"],
                IconAutopilot = _localizer["Boat.Icon.Autopilot"],
                IconEngine = _localizer["Boat.Icon.Engine"],
                IconFire = _localizer["Boat.Icon.Fire"],
                IconFishing = _localizer["Boat.Icon.Fishing"],
                IconInflatable = _localizer["Boat.Icon.Inflatable"],
                IconLifeRaft = _localizer["Boat.Icon.LifeRaft"],
                IconMap = _localizer["Boat.Icon.Map"],
                IconRadar = _localizer["Boat.Icon.Radar"],
                IconSignal = _localizer["Boat.Icon.Signal"],
                IconSolar = _localizer["Boat.Icon.Solar"],
                IconGrill = _localizer["Boat.Icon.Grill"],
                IconFridge = _localizer["Boat.Icon.Fridge"],
                IconFreezer = _localizer["Boat.Icon.Freezer"],
                OverlapText = _localizer["Boat.Overlap.Text"],
                OverlapTitle = _localizer["Boat.Overlap.Title"]
            };

            return View(model);
        }
    }
}

Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using sailwithdivine.com.Models.ContactUs;

namespace sailwithdivine.com.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly IStringLocalizer<Resource> _localizer;

        public ContactUsController(IStringLocalizer<Resource> localizer)
        {
            _localizer = localizer;
        }
        public IActionResult Index()
        {
            var model = new ContactUsViewModel
            {
                Title = _localizer["ContactUs.Title"],
                Text = _localizer["ContactUs.Text"]
            };

            return View(model);
        }
    }
}

Controllers/CrewController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using sailwithdivine.com.Models.Crew;

namespace sailwithdivine.com.Controllers
{
    public class CrewController : Controller
    {
        private readonly IStringLocalizer<Resource> _localizer;

        public CrewController(IStringLocalizer<Resource> localizer)
        {
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            var model = new CrewViewModel
            {
                Title = _localizer["Crew.Title"]
            };

            return View(model);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using sailwithdivine.com.Models;
using sailwithdivine.com.Models.Home;

namespace sailwithdivine.com.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IStringLocalizer<Resource> _localizer;

        public HomeController(ILogger<HomeController> logger, IStringLocalizer<Resource> localizer)
        {
            _logger = logger;
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            var atlanticDate = DateTime.Parse("2020-11-22");
            var daysLeft = (atlanticDate.Date - DateTime.UtcNow.Date).TotalDays;

            var result = "";

            if(DateTime.UtcNow.Date.CompareTo(atlanticDate) > 0 || DateTime.UtcNow.Date.CompareTo(atlanticDate) == 0)
            {
                result = _localizer["Home.Countdown.Crossing"];
            }
            else
            {
                result = $"{daysLeft} {_localizer["Home.Countdown.Days"]}";
            }


            var model = new HomeViewModel
            {
                IconContactUsText = _localizer["Home.Icon.ContactUs"],
                IconCrewText = _localizer["Home.Icon.Crew"],
                IconInstagramText = _localizer["Home.Icon.Instagram"],
                IconShipText = _localizer["Home.Icon.Ship"],
                PositionButtonText = _localizer["Home.Position.Button"],
                PositionText = _localizer["Home.Position.Text"],
                CountdownTitle = _localizer["Home.Countdown.Title"],
                CountdownDays = result
            };

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PositionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using sailwithdivine.com.Models.Position;

namespace sailwithdivine.com.Controllers
{
    public class PositionController : Controller
    {
        private readonly IStringLocalizer<Resource> _localizer;

        public PositionController(IStringLocalizer<Resource> localizer)
        {
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            var model = new PositionViewModel
            {
                Title = _localizer["Position.Title"],
                Subtitle = _localizer["Position.Subtitle"]
            };

            return View(model);
        }
    }
}

Controllers/SailWithUsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using sailwithdivine.com.Models.SailWithUs;

namespace sailwithdivine.com.Controllers
{
    public class SailWithUsController : Controller
    {
        private readonly IStringLocalizer<Resource> _localizer;

        public SailWithUsController(IStringLocalizer<Resource> localizer)
        {
            _localizer = localizer;
        }
        public IActionResult Index()
        {
            var model = new SailWithUsViewModel
            {
                HeroTitle = _localizer["SailWithUs.Hero.Title"],
                Section1Title = _localizer["SailWithUs.Section1.Title"],
                Section1Text = _localizer["SailWithUs.Section1.Text"],
                Section2Title = _localizer["SailWithUs.Section2.Title"],
                Section2Text = _localizer["SailWithUs.Section2.Text"],
                Section3Title = _localizer["SailWithUs.Section3.Title"],
                Section3Text = _localizer["SailWithUs.Section3.Text"],
                Section4Title = _localizer["SailWithUs.Section4.Title"],
                Section4Text = _localizer["SailWithUs.Section4.Text"]
            };

            return View(model);
        }
    }
}

Views/Home/Crew.cshtml
@{
    ViewData["Title"] = "Crew";
}

<div class="absolute-header">
        <h1 class="absolute-header__title">Crew</h1>
        <p>Meet the crew that are, or have been onboard Divine</p>
</div>

<div class="content crew__content">
    <h2 class="crew__section-title">Current crew</h2>
    <div class="card__container">

        <div class="card__item">
            <div class="card__item-container">
                <div class="overlay-gradiant"></div>
                <div class="card__img-holder">
                    <img alt="Oscar" src="~/Content/Crew/oscar.jpg" class="card__img" />
                </div>
                <div class="card__item-info">
                    <span>Oscar</span>
                    <svg class="icon icon-sweden"><use xlink:href="#icon-sweden"></use></svg>
                </div>
            </div>
        </div>

        <div class="card__item">
            <div class="card__item-container">
                <div class="overlay-gradiant"></div>
                <div class="card__img-holder">
                    <img alt="Totte" src="~/Content/Crew/totte.jpg" class="card__img" />
                </div>
                <div class="card__item-info">
                    <span>Totte</span>
                    <svg class="icon icon-sweden"><use xlink:href="#icon-sweden"></use></svg>
                </div>
            </div>
        </div>
    </div>

    <h2 class="crew__section-title">Previous crew</h2>

    <div class="card__container">
        <div class="card__item">
            <div class="card__item-container">
                <div class="overlay-gradiant"></div>
                <div class="card__img-holder">
                    <img alt="Simon" src="~/Content/Crew/simon.jpg" class="card__img" />
                </div>
                <div class="card__item-info">
                    <span>Simon</span>
                    <svg class="icon icon-sweden"><use xlink:href="#icon-sweden"></use></svg>
                </div>
            </div>
        </div>

        <div class="card__item">
            <div class="card__item-container">
                <div class="overlay-gradiant"></div>
                <div class="card__img-holder">
                    <img alt="Janne" src="~/Content/Crew/janne.jpg" class="card__img" />
                </div>
                <div class="card__item-info">
                    <span>Janne</span>
                    <svg class="icon icon-sweden"><use xlink:href="#icon-sweden"></use></svg>
                </div>
            </div>
        </div>

    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "SailWithDivine";
}

@model sailwithdivine.com.Models.Home.HomeViewModel;

<section class="img-header">
    <div class="img-header__image" style="background-image:url('Content/bowangel.jpg')"></div>
    <div class="img-header__text-container">
        <h1>Sail with Divine</h1>
    </div>
    <div class="img-header__icon-container">
        <a asp-controller="Boat" asp-action="Index">
            <div class="img-header__icon-item">
                <svg class="icon icon-boat"><use xlink:href="#icon-boat"></use></svg>
                <span>@Model.IconShipText</span>
            </div>
        </a>
        <a href="https://www.instagram.com/sailwithdivine/" target="_blank">
            <div class="img-header__icon-item">
                <svg class="icon icon-instagram-sketched"><use xlink:href="#icon-instagram-sketched"></use></svg>
                <span>@Model.IconInstagramText</span>
            </div>
        </a>
        <a asp-controller="Crew" asp-action="Index">
            <div class="img-header__icon-item">
                <svg class="icon icon-user"><use xlink:href="#icon-user"></use></svg>
                <span>@Model.IconCrewText</span>
            </div>
        </a>
        <a asp-controller="ContactUs" asp-action="Index">
            <div class="img-header__icon-item">
                <svg class="icon icon-email"><use xlink:href="#icon-email"></use></svg>
                <span>@Model.IconContactUsText</span>
            </div>
        </a>
    </div>
</section>

<section class="overlap__container">
    <div class="content overlap__content">
        <div class="overlap__text-container">
            <h2>Segla med oss!</h2>
            <p>På båten använder vi oss av paying crew vilket betyder att man är en del i crewet och hjälper till med att lägga loss, att segla, laga mat och att städa.</p>
            <a asp-controller="SailWithUs" asp-action="Index" class="button button--secondary">Läs mer</a>
        </div>
        <div class="overlap__image overlap__image--top" style="background-image:url('../Content/sailwithus.jpg')">
        </div>
    </div>
</section>

<section class="intro">
    <div class="content">
        <h2 class="intro__title">Position</h2>
        <div class="intro__container">
            <svg class="icon icon-pin"><use xlink:href="#icon-pin"></use></svg>
            <div class="intro__text-container">
                <p>@Model.PositionText</p>
                <a asp-controller="Position" asp-action="Index" class="button">@Model.PositionButtonText</a>
            </div>
        </div>
    </div>
</section>

<section class="absolute-header">
    <div class="absolute-header__image" style="background-image:url('Content/logodivine.png');"></div>
</section>

<section class="countdown">
    <div class="content">
        <div class="countdown__circle">
            <h4 class="countdown__text">@Model.CountdownTitle</h4>
            <h2 class="countdown__text">@Model.CountdownDays</h2>
            <h4 class="countdown__text">Crew status: full</h4>
        </div>
    </div>
</section>