Models/Header/HeaderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace sailwithdivine.com.Models.Header
{
    public class HeaderViewModel
    {
        public CountryModel Current{ get; set; }
        public CountryModel AvailableCountry { get; set; }
    }

    public class CountryModel
    {
        public string CountryFlag { get; set; }
        public string CountryName { get; set; }
        public string Culture { get; set; }
    }
}

Components/CookiebannerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using sailwithdivine.com.Models.Cookiebanner;

namespace sailwithdivine.com.Components
{
    public class CookiebannerViewComponent : ViewComponent
    {
        private readonly IStringLocalizer<Resource> _localizer;

        public CookiebannerViewComponent(IStringLocalizer<Resource> localizer)
        {
            _localizer = localizer;
        }
        public IViewComponentResult Invoke()
        {

            var model = new CookiebannerViewModel
            {
                Text = _localizer["Cookiebanner.Text"]
            };

            return View(model);
        }


    }
}

Components/HeaderViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using sailwithdivine.com.Models.Header;
using System;
using System.Linq;

namespace sailwithdivine.com.Components
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly IStringLocalizer<Resource> _localizer;

        public HeaderViewComponent(IStringLocalizer<Resource> localizer)
        {
            _localizer = localizer;
        }
        public IViewComponentResult Invoke()
        {
            var currentCultureName = Request.HttpContext.Features.Get<IRequestCultureFeature>().RequestCulture.UICulture.Name;

            var otherCultureName = currentCultureName.Equals("sv-SE") ? "en-US" : "sv-SE";

            var model = new HeaderViewModel
            {
                Current = new CountryModel
                {
                    CountryName = _localizer[$"Header.Country.{currentCultureName}"],
                    CountryFlag = $"icon-{currentCultureName}",
                    Culture = currentCultureName

                },
                AvailableCountry = new CountryModel
                {
                    CountryName = _localizer[$"Header.Country.{otherCultureName}"],
                    CountryFlag = $"icon-{otherCultureName}",
                    Culture = otherCultureName
                }
            };

            return View(model);
        }


    }
}

Controllers/LanguageController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;


namespace sailwithdivine.com.Controllers
{
    public class LanguageController : Controller
    {
        public IActionResult SetLanguage(string culture, string returnUrl)
        {

            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

Views/Shared/Components/Header/Default.cshtml
@model sailwithdivine.com.Models.Header.HeaderViewModel;

@{ 
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<nav class="navbar">
    <div class="navbar__container">
        <div class="navbar__logo">
            <a href="/">
                <img alt="logo" src="~/Content/logo-round.png" />
            </a>
        </div>
        <div class="navbar__flag-container js-flag-selector noSelect">
            <svg class="icon @Model.Current.CountryFlag"><use xlink:href="#@Model.Current.CountryFlag"></use></svg>
            <div class="navbar__flag-selector-container js-flag-selector-container">
                <a asp-controller="Language" asp-action="SetLanguage" asp-all-route-data="@(new Dictionary<string, string> { { "culture", Model.AvailableCountry.Culture }, { "returnUrl" , returnUrl} })">
                    <span>@Model.AvailableCountry.CountryName</span>
                    <svg class="icon @Model.AvailableCountry.CountryFlag"><use xlink:href="#@Model.AvailableCountry.CountryFlag"></use></svg>
                </a>
            </div>
        </div>
    </div>
</nav>